apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tpfoyer
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - |
            until nc -z mysql 3306; do echo "waiting for mysql"; sleep 5; done

      containers:
      - name: tpfoyer
        image: lamisbenhassine/tpfoyer:1.0
        ports:
          - containerPort: 8080
        env:
          - name: SERVER_PORT
            value: "8080"

          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/tpfoyerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

          - name: SPRING_DATASOURCE_USERNAME
            value: root

          - name: SPRING_DATASOURCE_PASSWORD
            value: root

          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update

          - name: SPRING_JPA_DATABASE_PLATFORM
            value: org.hibernate.dialect.MySQLDialect

