apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tpfoyer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: tpfoyer
    spec:
      containers:
        - name: tpfoyer
          image: lamisbenhassine/tpfoyer:1.0
          ports:
            - containerPort: 8080
